### PR TITLE
Feature create roles on join

### PR DESCRIPTION
**Pull request by IGLADI**
1 general category and 1 category per (main) guild are created with their corresponding channels when the bot joins a server.
Everyone has aces to the general category while only the guild members have access to the guild specific category

Only the main channels have been created, not the feature dependent channels.

DO NOT ACCEPT [until main guilds have been created](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/issues/5) (it uses guild.name) this is temp for review and I used a mock object for testing myself but it will not work without the main guilds merged _before._

Fix: [Main Text/voice discord channels auto created on server join Issue #6](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/issues/6) & [Create main guild roles Issue #28](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/issues/28)

### CODE REVIEW

**Comment by LordTlasT** [comment]
Currenlty reviewing this.

**Review by LordTlasT — COMMENTED** [review]
There is a lot of repeating code that could be turned into a loop.

You could use this structure for channels
{ {channel_type, name}, {channel_type, name}, ... }
And do the same thing for the categories

**Comment by LordTlasT** [comment]
Remove the ENGINE staments.  These should only be added later if required by the specificiation.

**Comment by LordTlasT** [comment]
remove your main function, we will not run this python code, but rather import it.

**Comment by LordTlasT** [comment]
Your connection is method is everything but secure, please import it from a seperate file like data.py or config.json

**Comment by IGLADI** [comment]
> There is a lot of repeating code that could be turned into a loop.
> 
> You could use this structure for channels { {channel_type, name}, {channel_type, name}, ... } And do the same thing for the categories

Fixes

**Comment by LordTlasT** [comment]
Currently reviewing this.

- rewrite elif to match case
- move hardcoded lists to a seperate file
- maybe it is possibel to use this enumeration instead of strings: https://discordpy.readthedocs.io/en/stable/api.html?highlight=forum#discord.ChannelType.forum

**Comment by IGLADI** [comment]
> * rewrite elif to match case

Done

> * move hardcoded lists to a seperate file

Done


> * **maybe** it is possible to use reference to the functions in the lists like so:
>   { create_text_channel: "announcements", create_text_channel: "off-topic", create_forum: "questions", ... }

Can be done, but don't think it's worth it for now, will come back to this when at least the MVP is done.

**Comment by LordTlasT** [comment]
fix your conflicts with main.

**Pull request merged**
