### PR TITLE
Database

### PR DESCRIPTION
**Pull request by HGThinh**
# Database, Create database and table with SQL, create python file with connection and insert data functions to update data in the database [^1]

Modifications[^2]
Additions[^3]
Additional remarks[^4]\*\*

[^1]: Name and description of the issue

-   Name: Database
-   Issue: Create database and table with SQL, create python file with connection and insert data functions to update data in the database
    [^2]: Modifications
-   Classed modified + description: update table building, delete SQL/update_database.sql, update database.py, create database etherealhyperspacebattleshipsdb, create table building, guild, location, cargo, planet, player, resource, ship ,speed 
    [^3]: Files added
-   Classes added + description: database.py. SQL folder/database.sql
    [^4]: Additional remarks (e. a. documentation needs to be updated)
    > [!NOTE]
    > Contact the UI dev for everything UI related
    > Contact the documentation master in case documentation needs to be modified

### CODE REVIEW

**Comment by LordTlasT** [comment]
delete what isn't related to the pull request. like `commands modified` ...

**Comment by LordTlasT** [comment]
Please use mariadb instead and add it to the requirements.txt file

**Comment by LordTlasT** [comment]
remove your main function, we will not run this python code, but rather import it.

this results into removing your unneeded import sys instruction

**Comment by LordTlasT** [comment]
Your connection is method is everything but secure, please import it from `config.json` and then post the login information in discord `config-json` channel.

**Comment by LordTlasT** [comment]
Remove the ENGINE staments. These should only be added later if required by the specificiation.

**Comment by LordTlasT** [comment]
you did not delete your exit function.  This is probably a bug in your code.

**Comment by IGLADI** [comment]
Earth = C4MPU5 K441, make cool names for other planets
Announcement channel Id not needed per guild: can be calculated at runtime (category name=guild name=>announcements channel) 
"DROP DATABASE IF EXISTS `ethbdb`;
CREATE DATABASE `ethbdb`;
USE `ethbdb`;" dangerous if rerunned for some reason 
ship should be linked to modules

**Comment by LordTlasT** [comment]
> Earth = C4MPU5 K441, make cool names for other planets

his would be a more fitting for the documentation master @luluwaza 
> "DROP DATABASE IF EXISTS ethbdb;
> CREATE DATABASE ethbdb;
> USE ethbdb;" dangerous if rerunned for some reason

This file is meant to be run on your local machine for testing and should only be run once. It creates the database, a file that creates the database again on rerun is a bit stupid so I added this functionality to 'reset' the database when rerun.

**Pull request merged**
