### PR TITLE
50 feature trading system

### PR DESCRIPTION
**Pull request by IGLADI**
# Description[^1]
issue: [Add trading for resources #50](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/50)

#### Modifications[^2]
moved /pay to trade_cog.py

#### Additions[^3]
Added /give_resources & /trade 

#### Additional remarks[^4]
The trading is implemented with discord buttons and everything (discord modal paginators), the UI dev will still need to print nice messages with tabulate

    
[^1]: Description of the pull request.
[^2]: Modifications, commands modified and explanation.
[^3]: Files added, commands added and explanation.
[^4]: Additional remarks (e. a. documentation needs to be updated)

### CODE REVIEW

**Comment by LordTlasT** [comment]
I added implementation of database, but I couldn't get the ui/trade_menu.py to work properly. Could you please fix this for me?

**Comment by LordTlasT** [comment]
Still need to do:
- use constants instead of hardcoded values (modal[0]
- update the requirements.txt file
- integrate with database

**Comment by IGLADI** [comment]
>use constants instead of hardcoded values (modal[0]

U sure that's the right branch? didn't find that 

>update the requirements.txt file

done
>integrate with database

done

**Comment by LordTlasT** [comment]
> U sure that's the right branch? didn't find that
search for [0], it's modals and uppermodals, but there may be more

**Comment by IGLADI** [comment]
>search for [0], it's modals and uppermodals, but there may be more

yup mb, was resolved in another branch so I completly forgot it here

**Comment by LordTlasT** [comment]
remove the prints -> async def trade

**Comment by LordTlasT** [comment]
change to if and if
```py
        if amount < 0:
            if recipient_player.money < abs(amount):
                await interaction.response.send_message(
                    "The recipient doesn't have enough money to send.", ephemeral=True
                )
                return
        else:
            if sender.money < abs(amount):
                await interaction.response.send_message("You don't have enough money to send.", ephemeral=True)
                return
                ```

**Comment by LordTlasT** [comment]
remove welcome_ui.py

**Comment by LordTlasT** [comment]
I cannot /mine after registering, error in register logic ? conflict with check_player_exists

**Comment by IGLADI** [comment]
This is implemented in #83 will close this one.

**Pull request closed without merging**
