### PR TITLE
Feature implmenet help travel radar

### PR DESCRIPTION
**Pull request by ThomasKnoops**
# Description[^1]
issue: 
 - https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/45 
 - https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/43 
 - https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/59
 - https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/58
 - https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/1
 - https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/54

#### Modifications[^2]
 - Updated the /help function to now work with an input field
 - Update /mine to only work when on a planet
 - Re-added C4MPU5 K441 (removed earth)

#### Additions[^3]
 - Added new functions to travel
 - Added new function to scan the area around you for people/planets
 - Bot kicks himself from the server if he is added to a privat server instead of a community server

<br>

[^1]: Description of the pull request.
[^2]: Modifications, commands modified and explanation.
[^3]: Files added, commands added and explanation.

### CODE REVIEW

**Comment by LordTlasT** [comment]
Please edit the description.

**Comment by ThomasKnoops** [comment]
done

**Comment by IGLADI** [comment]
Fix your merge conflicts (should be 2s dw)

**Comment by ThomasKnoops** [comment]
Ready for review

**Comment by IGLADI** [comment]
Merge main (also implement the new help ui with your /help command)

Maybe set a dropdown menu like this for selecting /help pages (I can do that If you merge main)
image

should use player.name
image

Am I still at mercury + can't I cancel a flight?
image

If I'm really on mercury why can't I mine? maybe say I can't mine while traveling
image

mining X times instant? shouldn't it take some time (I can add a loading animation, should be cancelable too)=>make a reusable loading animation function
image

Say I can also mine on asteroid=>say you can't mine the void will be simpeler
image

Please use "check_registered" and not check_player_exists
image

Use banners from main (I can do this)
image

**Pull request merged**
