### PR TITLE
Feature advenced UI

### PR DESCRIPTION
**Pull request by IGLADI**
TODO after trading-system PR

# Description[^1]
issues: 
[UI for command ship_info #39](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/39)
[Ui inventory #63](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/63)
[Ui energy generator #64](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/64)
[Ui /balance #65](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/65)
[Ui trading #66](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/66)
[Ui ship #67](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/issues/67)

#### Modifications[^2]
Updated toggle generator to use on/off instead of True/False.
Trade modification:Deny offer if everything is 0 and moved TradeModal to the UI package.
Fixed trade paginator's first page menu.

#### Additions[^3]
Made normal, processing, done, and error banners.
All commands are updates with those banners (beside casino ofc)
Completed trades UI by sending DMs & showing trade resumes.

<br>

[^1]: Description of the pull request.
[^2]: Modifications, commands modified and explanation.
[^3]: Files added, commands added and explanation.
[^4]: Additional remarks (e. a. documentation needs to be updated)

### CODE REVIEW

**Comment by LordTlasT** [comment]
- duplicate requirements
- in /help commands should be put in verbatim with backticks \`/command\`, `/command`
- rename upgrade_ship to upgrade_module
- use player.name instead of interaction or member, because later on we will have names shared across user, I will rename this in the database. Also /give_resource and /pay do not use the same name so it is confusing
- rename send_or_receive money to transaction_action or something in the likes of this.
- still need to do info for modules specificly
image
- https://cs50.harvard.edu/python/2022/notes/9/#map
 
image
- seperate function might be useful because you're using this logic quite often
- remove welcome_ui.py
- add docstring to 'helper' functions, at least the ones in utils.py
- the loading moves when it's edited, this could be solved by editing an empty messageg and then showing the cargo

**Comment by IGLADI** [comment]
> still need to do info for modules specificly

should be another issue linked to all the /help ?
> add docstring to 'helper' functions, at least the ones in utils.py

check_registered seems straight forward to me, what else would need some?

All the rest is fixed

**Comment by LordTlasT** [comment]
please your print statement, this brings great shame upon our projects I hope you understand.

**Comment by LordTlasT** [comment]
> check_registered seems straight forward to me, what else would need some?

This will be another teammate's job, whom will have a better critical look.
LGTM

**Pull request merged**
